branch-defaults:
  master:
    environment: env-dev
    group_suffix: null
  production:
    environment: env-prod
global:
  application_name: hello-cicd
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
